export const SET_LISTA_PRODUTOS = '@produtos/SET_LISTA_PRODUTOS';
export const SET_LISTA_PRODUTOS_ESTOQUE = '@produtos/SET_LISTA_PRODUTOS_ESTOQUE';
export const SET_LISTA_PRODUTOS_ESTOQUE_PRECO = '@produtos/SET_LISTA_PRODUTOS_ESTOQUE_PRECO';
